### ISSUE TITLE
Some minor notes

### ISSUE THREAD

**Issue by BGmot** [aeciopires/zabbix-scripts#1]
Hi,

feel free to close this Issue but I just wanted to make some minor remarks on the code.
1. [Lines 42 - 45](https://github.com/aeciopires/zabbix-scripts/blob/main/scripts/updateZabbixServerHostInterface.py#L42) you specify defaults but later in line 57 you fail anyway if one of the vars is not provided via environment variables, so it is kind of pointless to specify defaults).
2. At the end I see commented `zapi.user.logout()`, is there a reason for that? If we don't log out this session will be active forever (or for a long time) in sessions table.
3. All this can be done in pure /bin/sh with curl (Python is kind of heavy) but it will be totally different script -)

Great idea with the script!

**Comment by aeciopires** [comment]
Hi @BGmot!

Thanks for your comments!

1- It was on purpose. I'm not a Python expert, so I didn't want to miss the example of how to define default values ​​in case of need... In this case, I've prioritized the script failing if no one has defined the variables. In another version, I will remove this default values ​​setting as I now have minimal backup and versioning in git. ;-) But it was very well observed. 

2- I commented out this call, because unfortunately it is failing and I don't understand why... Whenever I run it, it fails with the error.

```bash
Traceback (most recent call last):
  File "updateZabbixServerHostInterface.py", line 120, in <module>
    zapi.user.logout()
  File "/home/aeciopires/.local/lib/python3.8/site-packages/zabbix_api.py", line 230, in logout
    raise ZabbixAPIException("No authentication information available.")
zabbix_api.ZabbixAPIException: No authentication information available.
```

3- Yes, I thought about this approach, but I wanted to avoid problems with the lack of the correct version of Python that I certified in the test, with the lack of the library or having to wait every time to download and install packages and eventually having to deal with issues because people may have different types of environments to run this helm chart.

**Comment by BGmot** [comment]
Try
```
zapi.logout()
```

**Comment by aeciopires** [comment]
Thanks @BGmot! It works.
I will generate a new version.

**Comment by aeciopires** [comment]
Hi @BGmot!

I fixed this issue with the commit https://github.com/aeciopires/zabbix-scripts/commit/e9d781461c72002ec5a211e2284ae167c49a4ab2 and generated the version v0.1.1
